#!/usr/bin/env bash
# Generate the Ansible inventory from lab.conf, so addresses are never
# maintained in two places.

. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib/common.sh"

VARIANT="full"
CONF=""
OUT=""

while [ $# -gt 0 ]; do
    case "$1" in
        --variant) VARIANT="$2"; shift 2 ;;
        --output)  OUT="$2";     shift 2 ;;
        --config)  CONF="$2";    shift 2 ;;
        -h|--help) echo "usage: generate-inventory.sh [--variant full|light] [--output FILE]"; exit 0 ;;
        *) die "unknown option: $1" ;;
    esac
done

load_config "${CONF:-}"
OUT="${OUT:-$REPO_DIR/inventory/hosts.ini}"
mkdir -p "$(dirname "$OUT")"

root_dc="$(lab_root_dc_name "$VARIANT")"
root_ip="$(lab_root_dc_ip   "$VARIANT")"

dcs=""; members=""; workstations=""; hosts=""
while IFS= read -r record; do
    [ -n "$record" ] || continue
    name="$(vm_name "$record")"
    ip="$(vm_ip "$record")"
    role="$(vm_field "$record" 7)"
    hosts="$hosts$(printf '%-7s ansible_host=%s' "$name" "$ip")"$'\n'
    case "$role" in
        dc_root|dc_child) dcs="$dcs$name"$'\n' ;;
        member)           members="$members$name"$'\n' ;;
        workstation)      workstations="$workstations$name"$'\n' ;;
    esac
done <<EOF
$(lab_vms "$VARIANT")
EOF

{
    echo "# Generated by scripts/generate-inventory.sh from lab.conf."
    echo "# Edit lab.conf and regenerate; changes here are overwritten."
    echo "# variant: $VARIANT"
    echo
    echo "[windows]"
    printf '%s' "$hosts"
    echo
    echo "[domain_controllers]"
    printf '%s' "$dcs"
    echo
    echo "[member_servers]"
    printf '%s' "$members"
    echo
    echo "[workstations]"
    printf '%s' "$workstations"
    echo
    echo "# Everything that must end up joined to the domain."
    echo "[domain_members:children]"
    echo "member_servers"
    echo "workstations"
    echo
    echo "[windows:vars]"
    echo "ansible_connection=winrm"
    echo "ansible_winrm_transport=basic"
    echo "ansible_port=5985"
    echo "ansible_winrm_scheme=http"
    echo "ansible_winrm_server_cert_validation=ignore"
    echo "ansible_user=Administrator"
    echo "ansible_password=$GOAD_ADMIN_PASSWORD"
    echo
    echo "domain_name=$GOAD_DOMAIN"
    echo "domain_netbios=$GOAD_NETBIOS"
    echo "forest_mode=$GOAD_FOREST_MODE"
    echo "domain_admin_password=$GOAD_ADMIN_PASSWORD"
    echo "safe_mode_password=$GOAD_SAFEMODE_PASSWORD"
    echo "root_dc_name=$root_dc"
    echo "root_dc_ip=$root_ip"
} > "$OUT"

log_ok "wrote $OUT"
log_dim "$(grep -c 'ansible_host=' "$OUT") hosts, domain $GOAD_DOMAIN, root DC $root_dc at $root_ip"
